print("Welcome to the tip calculator")
total_bill = int(input("what was the total bill? "))
tip = int(input("How much tip would you like to give 10, 20 or 15? "))
people = int(input("How many people to split the bill? "))
print(f"Each person should pay {(total_bill + total_bill / 100 * tip)/people}")